export default {
  tintColor: '#1B255C',
  tintColorSecondary: '#E35558',
  tintColorSecondaryLight: '#ba8081',
  primaryBg: '#141C42',
  primaryBorder: '#323b63',
  subTitle: '#CACBD5',
  title: '#FFF',
  textColorGrey: '#CACBD5',
  error: '#dd2e3a',
  tintColorDisabled: '#569aff',
  white: '#FFFFFF',
  tintColorGreyed: '#f4f8ff',
  tintColorGreyedDark: '#d8e8ff',
};